version: '3.8'
services:
  backend:
    build: ../backend
    container_name: havit-backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped
    command: sh -c "npm run db:migrate && npm run start:dev"
